services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: 'redis:latest'
    container_name: redis

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx
    ports:
      - '8080:80' # Change Nginx to use port 8080 on the host
      - '3080:3080' # Expose WebSocket port separately for client
    depends_on:
      - api
      - client

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: complex/api:latest
    container_name: api
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    image: complex/worker:latest
    container_name: worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: complex/client:latest
    container_name: client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - HOST=0.0.0.0
      - WDS_SOCKET_PORT=3080
