services:
  client:
    image: 'nickchendev/multi-client'
    mem_limit: 128m
    hostname: client

  server:
    image: 'nickchendev/multi-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT

  worker:
    image: 'nickchendev/multi-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  nginx:
    image: 'nickchendev/multi-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
