name: Deploy Multi-Container

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for testing (using Dockerfile.dev)
        run: docker build -t nickdev/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests in Docker container
        run: docker run -e CI=true nickdev/react-test npm test

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - run: docker build -t nickchendev/multi-client ./client
      - run: docker build -t nickchendev/multi-nginx ./nginx
      - run: docker build -t nickchendev/multi-server ./server
      - run: docker build -t nickchendev/multi-worker ./worker

      - run: docker push nickchendev/multi-client
      - run: docker push nickchendev/multi-nginx
      - run: docker push nickchendev/multi-server
      - run: docker push nickchendev/multi-worker
