name: Deploy Multi-Container

on:
  push:
    branches: ['main']

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for testing (using Dockerfile.dev)
        run: docker build -t nickdev/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests in Docker container
        run: docker run -e CI=true nickdev/react-test npm test

  push-docker-hub:
    runs-on: ubuntu-latest
    needs: docker-test # Ensures tests run before image build and push to docker hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build docker images
        run: |
          docker build -t nickchendev/multi-client ./client
          docker build -t nickchendev/multi-nginx ./nginx
          docker build -t nickchendev/multi-server ./server
          docker build -t nickchendev/multi-worker ./worker

      - name: Push images to dockerhub
        run: |
          docker push nickchendev/multi-client
          docker push nickchendev/multi-nginx
          docker push nickchendev/multi-server
          docker push nickchendev/multi-worker

      - name: Generate deploy package (zip)
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-376578549272
          region: ap-southeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
